# Включаем всякую диагностическую дрянь фласка
DEBUG: True

# Больше диагностической дряни
TESTING: True

# Путь до базы данных, используемой приложением
# На винде нужно изобразить существующий путь
SQLALCHEMY_DATABASE_URI: 'sqlite:////tmp/postmaster.sqlite'

# Не разобрался что эта штука делает, но flask-sqlalchemy рекомендут это отключить
SQLALCHEMY_TRACK_MODIFICATIONS: false

# Секретный (никому не показывать) ключ для CSRF защиты формочек
SECRET_KEY: "top-secret-csrf-key"

# Это все настройки лога
# Flask.app сюда не смотрит, но зато будем смотреть мы
# Подробнее https://flask.palletsprojects.com/en/2.0.x/logging/
# А еще тутж https://docs.python.org/3/library/logging.html
LOG_CONFIG:
  version: 1
  disable_existing_loggers: false
  formatters:
    default:
      format: '[%(asctime)s] %(name)s <%(levelname)s>: %(message)s'

  handlers:
    wsgi:
      level: 'DEBUG'
      class: 'logging.StreamHandler'
      stream: 'ext://flask.logging.wsgi_errors_stream'
      formatter: 'default'

    console:
      level: 'DEBUG'
      class: 'logging.StreamHandler'
      stream: 'ext://sys.stdout'
      formatter: 'default'

  loggers:
    root:
      level: 'DEBUG'
      handlers: [ 'console' ]
      # handlers: [ 'wsgi', 'console' ]
